# -*- coding: utf-8 -*-

# mk42
# mk42/apps/core/migrations/0001_initial.py

# Generated by Django 1.11.2 on 2017-06-14 15:46

from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import (
    migrations,
    models,
)
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=256, verbose_name="name")),
                ("slug", autoslug.fields.AutoSlugField(blank=True, default="", editable=True, help_text="overwrite in creation", max_length=256, populate_from="name", verbose_name="slug")),
                ("description", models.TextField(blank=True, db_index=True, null=True, verbose_name="description")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name="created date/time")),
                ("updated", models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name="updated date/time")),
                ("active", models.BooleanField(db_index=True, verbose_name="active")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="owned", to=settings.AUTH_USER_MODEL, verbose_name="owner")),
            ],
            options={
                "ordering": ["-created"],
                "verbose_name": "group",
                "verbose_name_plural": "groups",
            },
        ),
    ]
