# -*- coding: utf-8 -*-

# mk42
# mk42/apps/core/migrations/0003_auto_20170614_1554.py

# Generated by Django 1.11.2 on 2017-06-14 15:54

from __future__ import unicode_literals

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20170614_1553"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="active"),
        ),
    ]
