# -*- coding: utf-8 -*-

# mk42
# mk42/apps/core/migrations/0004_membership.py

# Generated by Django 1.11.2 on 2017-06-18 10:22

from __future__ import unicode_literals
import uuid

from django.conf import settings
from django.db import (
    migrations,
    models,
)
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_auto_20170614_1554"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name="created date/time")),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="members", to="core.Group", verbose_name="group")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="user")),
            ],
            options={
                "ordering": ["-created"],
                "verbose_name": "membership",
                "verbose_name_plural": "membership",
            },
        ),
    ]
