# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import redactor.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170618_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='name')),
                ('description', redactor.fields.RedactorField(blank=True, db_index=True, null=True, verbose_name='description')),
                ('start', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='start date/time')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created date/time')),
            ],
            options={
                'ordering': ['-created', '-start'],
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(db_index=True, max_length=256, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.Group', verbose_name='group'),
        ),
    ]
