# -*- coding: utf-8 -*-

# mk42
# mk42/apps/core/migrations/0008_auto_20170704_2034.py

# Generated by Django 1.11.2 on 2017-07-04 20:34

from __future__ import unicode_literals

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20170703_1612"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="address",
            field=models.CharField(db_index=True, max_length=256, null=True, verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="event",
            name="start",
            field=models.DateTimeField(db_index=True, null=True, verbose_name="start date/time"),
        ),
    ]
