# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170704_2034'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('group', 'start')]),
        ),
    ]
