# -*- coding: utf-8 -*-

# mk42
# mk42/apps/core/migrations/0010_rsvp.py

# Generated by Django 1.11.3 on 2017-07-10 09:46

from __future__ import unicode_literals
import uuid

from django.conf import settings
from django.db import (
    migrations,
    models,
)
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0009_auto_20170705_1247"),
    ]

    operations = [
        migrations.CreateModel(
            name="RSVP",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name="created date/time")),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rsvp", to="core.Event", verbose_name="group")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rsvp", to=settings.AUTH_USER_MODEL, verbose_name="user")),
            ],
            options={
                "ordering": ["-created"],
                "verbose_name": "rsvp",
                "verbose_name_plural": "rsvp",
            },
        ),
    ]
