# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rsvp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp', to='core.Event', verbose_name='event'),
        ),
    ]
