# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170711_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(db_index=True, max_length=2048, null=True, verbose_name='address'),
        ),
    ]
