# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170716_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='approved',
            field=models.BooleanField(db_index=True, default=False, verbose_name='approved'),
        ),
    ]
