# -*- coding: utf-8 -*-

# mk42
# mk42/apps/core/migrations/0014_auto_20170718_0216.py

# Generated by Django 1.11.2 on 2017-07-18 02:16

from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_membership_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membership",
            name="approved",
        ),
        migrations.AddField(
            model_name="membership",
            name="active",
            field=models.BooleanField(db_index=True, default=False, verbose_name="active"),
        ),
    ]
