# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import mk42.apps.core.validators.event


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170811_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(db_index=True, null=True, validators=[mk42.apps.core.validators.event.validate_end], verbose_name='end date/time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(db_index=True, null=True, validators=[mk42.apps.core.validators.event.validate_start], verbose_name='start date/time'),
        ),
    ]
