# mk42
# mk42/apps/users/migrations/0002_auto_20170613_2124.py

# Generated by Django 1.11.2 on 2017-06-13 21:24

from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(error_messages={"unique": "A user with that username already exists."}, help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.", max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name="username"),
        ),
    ]
